name: "Setup yarn"
description: "Setup yarn with cache"
author: aki77
inputs:
  cacheKeyPrefix:
    description: "input description here"
    default: "yarn"
  installCommand:
    description: "Yarn install command"
    default: "yarn install"
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
runs:
  using: "node12"
  main: "dist/index.js"
